---
title: "p8105_hw2_mgg2153"
author: "mggn"
date: "9/25/2020"
output: github_document
---

## Hello and welcome to the second homework

The first order of business is to load the tidyverse!
```{r setup, include=FALSE}
library(tidyverse)
```


### Problem 2: NYC transit data

```{r nyc_transit}
transit_df = read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(line, station_name, station_latitude, station_longitude, 
         route1:route11, entrance_type, entry, ada) %>%
  mutate(
    entry = recode(entry, "YES" = "TRUE", "NO" = "FALSE")
  )

print(transit_df)
#I want to retain:  line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance
  
```

### Problem 3: FiveThirtyEight data

```{r 538_data}
pols_df = read_csv("./data/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon,into = c("year", "month", "day")) %>%
  mutate( 
    month_name = month.abb(mon)
  )
```
.
